### ISSUE TITLE
Test merges are erroring.

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation-server#103]
````
Enter command: testmerge 28900
Error: System.ServiceModel.FaultException: The server was unable to process the request du
e to an internal error.  For more information about the error, either turn on IncludeExcep
tionDetailInFaults (either from ServiceBehaviorAttribute or from the <serviceDebug> config
uration behavior) on the server in order to send the exception information back to the cli
ent, or turn on tracing as per the Microsoft .NET Framework SDK documentation and inspect
the server trace logs.

Server stack trace:
   at System.ServiceModel.Channels.ServiceChannel.ThrowIfFaultUnderstood(Message reply, Me
ssageFault fault, String action, MessageVersion version, FaultConverter faultConverter)
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operat
ion, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, Prox
yOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage me
thodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMess
age retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32
type)
   at TGServiceInterface.ITGServerUpdater.UpdateServer(TGRepoUpdateMethod updateType, Bool
ean push_changelog_if_enabled, UInt16 testmerge_pr)
   at TGCommandLine.TestmergeCommand.Run(IList`1 parameters)
   at TGCommandLine.RootCommand.Run(IList`1 parameters)
   at TGCommandLine.Program.RunCommandLine(IList`1 argsAsList)
````

**Comment by MrStonedOne** [comment]
https://github.com/tgstation/byond-server

**Comment by Cyberboss** [comment]
Fixed
