### ISSUE TITLE
(Discord?) Chat bots stop responding sometimes

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation-server#1083]
Confirmed in 4.4.0 and 4.4.1

Workaround is to reboot TGS

**Comment by Cyberboss** [comment]
@silicons Comment here when it happens please and I'll try and nag Jay

**Comment by Cyberboss** [comment]
aha! 
```
2020-07-17T08:07:10.2589866+00:00 (Instance:1|Job:|Request:|User:|Monitor:|Bridge:|Chat:): [ERR] Tgstation.Server.Host.Components.Chat.ChatManager: Message loop crashed! Exception: "System.InvalidOperationException: Provider not connected
   at Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.get_BotMention() in C:\projects\tgstation-server-tools\src\Tgstation.Server.Host\Components\Chat\Providers\DiscordProvider.cs:line 28
   at Tgstation.Server.Host.Components.Chat.ChatManager.ProcessMessage(IProvider provider, Message message, CancellationToken cancellationToken) in C:\projects\tgstation-server-tools\src\Tgstation.Server.Host\Components\Chat\ChatManager.cs:line 393
   at Tgstation.Server.Host.Components.Chat.ChatManager.MonitorMessages(CancellationToken cancellationToken) in C:\projects\tgstation-server-tools\src\Tgstation.Server.Host\Components\Chat\ChatManager.cs:line 436" ()
```
