### ISSUE TITLE
curl with -X POST does not work with the API

### ISSUE THREAD

**Issue by optimumtact** [tgstation/tgstation-server#1131]
**Describe the bug**
I have no idea what is going on here, but talking to the AUTH endpoint and using -X POST as a method, it seems to be completely ignored by the API

**To Reproduce**
```
cursed@raptor:~$ curl -H "Authorization:basic YWRtaW46SVNvbGVtbHlTd2VhclRvRGVsZXRlVGhlRGF0YURpcmVjdG9yeQ==" -H "Api: Tgstation.Server.Api/7.3.2" -X POST localhost:5050
cursed@raptor:~$ curl -H "Authorization:basic YWRtaW46SVNvbGVtbHlTd2VhclRvRGVsZXRlVGhlRGF0YURpcmVjdG9yeQ==" -H "Api: Tgstation.Server.Api/7.3.2" -X POSt localhost:5050
{"bearer":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoiMTYwMjQ3ODg5NiIsIm5iZiI6IjE2MDI0Nzc5OTYiLCJpc3MiOiJUZ3N0YXRpb24uU2VydmVyLkhvc3QiLCJhdWQiOiJUZ3N0YXRpb24uU2VydmVyLkFwaSJ9.sTlHOZieNN8-e36jlJSFhThx2sOO-eWxbFqc4R3OI68","expiresAt":"2020-10-12T05:01:36.8709627+00:00"}
cursed@raptor:~$ 
```
**Expected behavior**:
POST to work as a method and not require at least one lower case letter???

**Logs**
There is no log output when using POST

**Comment by Cyberboss** [comment]
```
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: POST request contains no Content-Length or Transfer-Encoding header.
   at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason, HttpMethod method)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.For(HttpVersion httpVersion, HttpRequestHeaders headers, Http1Connection context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.CreateMessageBody()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
```

Actually this is apparently curl's fault. See https://github.com/aspnet/KestrelHttpServer/issues/1234

**Comment by Cyberboss** [comment]
Still, I feel as though capitalization should not make a difference here. Reported: https://github.com/dotnet/aspnetcore/issues/26803
