### ISSUE TITLE
Rewrite Job Progress to be more managed

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation-server#1387]
i.e. A class per section

**Comment by Cyberboss** [comment]
Upgraded to bug as this can cause some git operations to fail

**Comment by Cyberboss** [comment]
```
System.ArgumentOutOfRangeException: Progress must be a value from 0-100! (Parameter 'progress')
Actual value was 270590.
2022-09-30T08:49:32.9501859+00:00 (Instance:1|Job:107|Request:POST /Repository|User:25|Monitor:|Bridge:|Chat:): [WRN] Tgstation.Server.Host.Components.Repository.Repository: Unable to push to temporary branch! ()
LibGit2Sharp.LibGit2SharpException: failed to write chunk header: The server returned an invalid or unrecognized response

   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_remote_push(RemoteHandle remote, IEnumerable`1 refSpecs, GitPushOptions opts)
   at LibGit2Sharp.Network.Push(Remote remote, IEnumerable`1 pushRefSpecs, PushOptions pushOptions)
   at LibGit2Sharp.Network.Push(Remote remote, String pushRefSpec, PushOptions pushOptions)
   at Tgstation.Server.Host.Components.Repository.Repository.<>c__DisplayClass44_0.<PushHeadToTemporaryBranch>b__0() in /home/runner/work/tgstation-server/tgstation-server/src/Tgstation.Server.Host/Components/Repository/Repository.cs:line 875
```
