### ISSUE TITLE
tgs fails to start

### ISSUE THREAD

**Issue by Cyprex** [tgstation/tgstation-server#1438]
**Describe the bug**
TGS version 5.5(latest as of this writing) fails to start up. A DB backup has been imported & one instance's GameStaticFiles have been copied over. The remainder(empty codemodifications & EventScripts) were NOT migrated. The initial startup just throws this error, indicating that mysql is trying to write to /tmp/, which it does not have permission for(permissions are rwxr-xr-x)

**Logs**
```
MySqlConnector.MySqlException (0x80004005): Can't create/write to file '/tmp/#sql-temptable-fd82-32-17.MAI' (Errcode: 13 "Permission denied")
   at MySqlConnector.Core.ResultSet.<ScanRowAsync>g__ScanRowAsyncAwaited|9_0(ResultSet resultSet, Task`1 payloadTask, Row row, CancellationToken token) in /_/src/MySqlConnector/Core/ResultSet.cs:line 240
   at MySqlConnector.Core.ResultSet.ReadAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ResultSet.cs:line 195
   at MySqlConnector.MySqlDataReader.ReadAsync(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 35
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.BufferedDataRecord.InitializeAsync(DbDataReader reader, IReadOnlyList`1 columns, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.InitializeAsync(IReadOnlyList`1 columns, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.InitializeAsync(IReadOnlyList`1 columns, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<>c__DisplayClass33_0`2.<<ExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Tgstation.Server.Host.Components.InstanceManager.<>c__DisplayClass26_1.<<StartAsync>b__0>d.MoveNext() in /home/runner/work/tgstation-server/tgstation-server/src/Tgstation.Server.Host/Components/InstanceManager.cs:line 400
```

**Server State: (please complete the following information):**
 - OS: Linux
 - Version: 5.5
 - Database Type/Version: MariaDB, whatever version ubuntu 22.04 ships by default
 - BYOND Version Used:
 - git Repository Used: fails during initial startup, before any could be installed
 - Origin Commit hash Used:
 - Active Test Merges:
 - Client Version:

**Additional context**

**Comment by Cyprex** [comment]
This happens with both the appsettings.yml from the old server & a newly created one

**Comment by Cyprex** [comment]
Full logs(contain several attempts to start the server: http://ix.io/4s7P
