### ISSUE TITLE
Unable to deploy on v5.7.1

### ISSUE THREAD

**Issue by Crossedfall** [tgstation/tgstation-server#1445]
**Describe the bug**
Attempting to deploy changes with static files (such as config/data) results in an exception on Windows.

**To Reproduce**
1. Deploy changes

**Expected behavior**
Changes are compiled and staged for deployment

**Logs**
```csharp
Tgstation.Server.Host.Components.StaticFiles.Configuration: No event scripts starting with ""PostCompile"" detected ()
Tgstation.Server.Host.System.ProcessExecutor: PID 14492 termination event completed ()
Tgstation.Server.Host.Components.Deployment.DreamMaker: Applying static game file symlinks... ()
Tgstation.Server.Host.Components.StaticFiles.Configuration: Ignoring static file ".tgsignore"... ()
Tgstation.Server.Host.Components.StaticFiles.Configuration: Symlinking "<dir>\Configuration\GameStaticFiles\config" to "<dir>\Game\c0811cbb-d5a6-468c-9d37-383b191773a2\config"... ()
Tgstation.Server.Host.Components.StaticFiles.Configuration: Symlinking "<dir>\Configuration\GameStaticFiles\data" to "<dir>\Game\c0811cbb-d5a6-468c-9d37-383b191773a2\data"... ()
Tgstation.Server.Host.Components.Deployment.DreamMaker: Cleaning compile directory... ()
Tgstation.Server.Host.Components.StaticFiles.Configuration: No event scripts starting with ""DeploymentCleanup"" detected ()
Tgstation.Server.Host.Jobs.JobManager: Job 162540 exited with error! ()
BetterWin32Errors.Win32Exception: ERROR_ALREADY_EXISTS: Cannot create a file when that file already exists.
   at Tgstation.Server.Host.IO.WindowsSymlinkFactory.<>c__DisplayClass0_0.<CreateSymbolicLink>b__0() in /home/runner/work/tgstation-server/tgstation-server/src/Tgstation.Server.Host/IO/WindowsSymlinkFactory.cs:line 41
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Tgstation.Server.Host.Components.StaticFiles.Configuration.<>c__DisplayClass23_0.<<SymlinkStaticFilesTo>b__2>d.MoveNext() in /home/runner/work/tgstation-server/tgstation-server/src/Tgstation.Server.Host/Components/StaticFiles/Configuration.cs:line 403
--- End of stack trace from previous location ---
   at Tgstation.Server.Host.Components.StaticFiles.Configuration.<>c__DisplayClass23_0.<<SymlinkStaticFilesTo>g__SymlinkBase|1>d.MoveNext() in /home/runner/work/tgstation-server/tgstation-server/src/Tgstation.Server.Host/Components/StaticFiles/Configuration.cs:line 378
--- End of stack trace from previous location ---
   at Tgstation.Server.Host.Components.StaticFiles.Configuration.SymlinkStaticFilesTo(String destination, CancellationToken cancellationToken) in /home/runner/work/tgstation-server/tgstation-server/src/Tgstation.Server.Host/Components/StaticFiles/Configuration.cs:line 411
   at Tgstation.Server.Host.Components.Deployment.DreamMaker.RunCompileJob(CompileJob job, DreamMakerSettings dreamMakerSettings, DreamDaemonLaunchParameters launchParameters, IByondExecutableLock byondLock, IRepository repository, IRemoteDeploymentManager remoteDeploymentManager, CancellationToken cancellationToken) in /home/runner/work/tgstation-server/tgstation-server/src/Tgstation.Server.Host/Components/Deployment/DreamMaker.cs:line 700
   at Tgstation.Server.Host.Components.Deployment.DreamMaker.RunCompileJob(CompileJob job, DreamMakerSettings dreamMakerSettings, DreamDaemonLaunchParameters launchParameters, IByondExecutableLock byondLock, IRepository repository, IRemoteDeploymentManager remoteDeploymentManager, CancellationToken cancellationToken) in /home/runner/work/tgstation-server/tgstation-server/src/Tgstation.Server.Host/Components/Deployment/DreamMaker.cs:line 708
   at Tgstation.Server.Host.Components.Deployment.DreamMaker.Compile(RevisionInformation revisionInformation, DreamMakerSettings dreamMakerSettings, DreamDaemonLaunchParameters launchParameters, IRepository repository, IRemoteDeploymentManager remoteDeploymentManager, JobProgressReporter progressReporter, Nullable`1 estimatedDuration, Boolean localCommitExistsOnRemote, CancellationToken cancellationToken) in /home/runner/work/tgstation-server/tgstation-server/src/Tgstation.Server.Host/Components/Deployment/DreamMaker.cs:line 526
   at Tgstation.Server.Host.Components.Deployment.DreamMaker.Compile(RevisionInformation revisionInformation, DreamMakerSettings dreamMakerSettings, DreamDaemonLaunchParameters launchParameters, IRepository repository, IRemoteDeploymentManager remoteDeploymentManager, JobProgressReporter progressReporter, Nullable`1 estimatedDuration, Boolean localCommitExistsOnRemote, CancellationToken cancellationToken) in /home/runner/work/tgstation-server/tgstation-server/src/Tgstation.Server.Host/Components/Deployment/DreamMaker.cs:line 555
   at Tgstation.Server.Host.Components.Deployment.DreamMaker.DeploymentProcess(Job job, IDatabaseContextFactory databaseContextFactory, JobProgressReporter progressReporter, CancellationToken cancellationToken) in /home/runner/work/tgstation-server/tgstation-server/src/Tgstation.Server.Host/Components/Deployment/DreamMaker.cs:line 326
   at Tgstation.Server.Host.Jobs.JobManager.RunJob(Job job, JobEntrypoint operation, CancellationToken cancellationToken) in /home/runner/work/tgstation-server/tgstation-server/src/Tgstation.Server.Host/Jobs/JobManager.cs:line 328

```

**Server State: (please complete the following information):**
 - OS: Windows Server
 - Version: 5.7.1
 - Database Type/Version: MariaDB
 - BYOND Version Used: 515.1604t2
 - Client Version: v4.17.0

**Comment by Cyberboss** [comment]
Fixed in #1446
