### ISSUE TITLE
Service crashed

### ISSUE THREAD

**Issue by MrStonedOne** [tgstation/tgstation-server#165]
````
Application: TGServerService.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Discord.Net.WebSockets.GatewaySocket+<ProcessMessage>d__17.MoveNext()

Exception Info: System.AggregateException
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean)
   at System.Threading.Tasks.Task.Wait(Int32, System.Threading.CancellationToken)
   at Discord.Net.WebSockets.WebSocket.<.ctor>b__33_1(System.Object, Discord.Net.WebSockets.TextMessageEventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b-CENSORED-9]].Invoke(System.Object, System.__Canon)
   at Discord.Net.WebSockets.WS4NetEngine.OnTextMessage(System.String)
   at Discord.Net.WebSockets.WS4NetEngine.OnWebSocketText(System.Object, WebSocket4Net.MessageReceivedEventArgs)
   at WebSocket4Net.WebSocket.FireMessageReceived(System.String)
   at WebSocket4Net.Command.Text.ExecuteCommand(WebSocket4Net.WebSocket, WebSocket4Net.WebSocketCommandInfo)
   at WebSocket4Net.WebSocket.ExecuteCommand(WebSocket4Net.WebSocketCommandInfo)
   at WebSocket4Net.WebSocket.OnDataReceived(Byte[], Int32, Int32)
   at WebSocket4Net.WebSocket.client_DataReceived(System.Object, SuperSocket.ClientEngine.DataEventArgs)
   at SuperSocket.ClientEngine.ClientSession.OnDataReceived(Byte[], Int32, Int32)
   at SuperSocket.ClientEngine.SslStreamTcpSession.OnDataRead(System.IAsyncResult)
   at System.Net.LazyAsyncResult.Complete(IntPtr)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(System.Object, IntPtr)
   at System.Net.Security._SslStream.ProcessFrameBody(Int32, Byte[], Int32, Int32, System.Net.AsyncProtocolRequest)
   at System.Net.Security._SslStream.ReadFrameCallback(System.Net.AsyncProtocolRequest)
   at System.Net.AsyncProtocolRequest.CompleteRequest(Int32)
   at System.Net.FixedSizeReader.CheckCompletionBeforeNextRead(Int32)
   at System.Net.FixedSizeReader.ReadCallback(System.IAsyncResult)
   at System.Net.LazyAsyncResult.Complete(IntPtr)
   at System.Net.ContextAwareResult.CompleteCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Net.ContextAwareResult.Complete(IntPtr)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(System.Object, IntPtr)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)

````

On that note, what is the best way to recover from this, the round is still going and what not, is there a way to start the service so it reattached, does it default to that, or would I have to wait for the round to end, task kill DD, then start the service?

**Comment by Cyberboss** [comment]
What I'll probably end up doing is making service restart in the game attach the service to that instance.

**Comment by Cyberboss** [comment]
Also

>Discord.Net

I'm actually going to die

**Comment by Cyberboss** [comment]
I think the real issue is the version of Discord.Net that we're using (which is out of date). I've been putting off updating it because the API is entirely different and there's .NET Core fuckery that needs to be done. I'll take another look at it

**Comment by Cyberboss** [comment]
Another paste from hippie

```
Application: TGServerService.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Discord.Net.WebSockets.GatewaySocket+<ProcessMessage>d__17.MoveNext()

Exception Info: System.AggregateException
   at System.Threading.Tasks.Task.Wait(Int32, System.Threading.CancellationToken)
   at Discord.Net.WebSockets.WebSocket.<.ctor>b__33_1(System.Object, Discord.Net.WebSockets.TextMessageEventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at Discord.Net.WebSockets.WS4NetEngine.OnTextMessage(System.String)
   at Discord.Net.WebSockets.WS4NetEngine.OnWebSocketText(System.Object, WebSocket4Net.MessageReceivedEventArgs)
   at WebSocket4Net.WebSocket.FireMessageReceived(System.String)
   at WebSocket4Net.Command.Text.ExecuteCommand(WebSocket4Net.WebSocket, WebSocket4Net.WebSocketCommandInfo)
   at WebSocket4Net.WebSocket.ExecuteCommand(WebSocket4Net.WebSocketCommandInfo)
   at WebSocket4Net.WebSocket.OnDataReceived(Byte[], Int32, Int32)
   at WebSocket4Net.WebSocket.client_DataReceived(System.Object, SuperSocket.ClientEngine.DataEventArgs)
   at SuperSocket.ClientEngine.ClientSession.OnDataReceived(Byte[], Int32, Int32)
   at SuperSocket.ClientEngine.SslStreamTcpSession.OnDataRead(System.IAsyncResult)
   at System.Net.LazyAsyncResult.Complete(IntPtr)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(System.Object, IntPtr)
   at System.Net.Security._SslStream.ProcessFrameBody(Int32, Byte[], Int32, Int32, System.Net.AsyncProtocolRequest)
   at System.Net.Security._SslStream.ReadFrameCallback(System.Net.AsyncProtocolRequest)
   at System.Net.AsyncProtocolRequest.CompleteRequest(Int32)
   at System.Net.FixedSizeReader.CheckCompletionBeforeNextRead(Int32)
   at System.Net.FixedSizeReader.ReadCallback(System.IAsyncResult)
   at System.Net.LazyAsyncResult.Complete(IntPtr)
   at System.Net.ContextAwareResult.CompleteCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Net.ContextAwareResult.Complete(IntPtr)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(System.Object, IntPtr)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
```

**Comment by Cyberboss** [comment]
The documentation for the new Discord.Net is virtually non existent ugh
