### ISSUE TITLE
Watch dog thread crashed

### ISSUE THREAD

**Issue by JamieH** [tgstation/tgstation-server#263]
```
Watch dog thread crashed: System.Exception: Hard restart failed: System.IO.IOException: The process cannot access the file 'TGServiceInterface.dll' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at TGServerService.TGStationServer.StartImpl(Boolean watchdog)
   at TGServerService.TGStationServer.Watchdog()
```

**Comment by Cyberboss** [comment]
FFS

**Comment by Cyberboss** [comment]
Did any user interaction trigger this?

**Comment by JamieH** [comment]
no.

**Comment by Cyberboss** [comment]
Answar me
