### ISSUE TITLE
NullReferenceException when fixing InstanceUser permissions

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation-server#735]
```
System.NullReferenceException: Object reference not set to an instance of an object.

   at Tgstation.Server.Host.Controllers.InstanceController.Update(Instance model, CancellationToken cancellationToken) in D:\tgstation-server\src\Tgstation.Server.Host\Controllers\InstanceController.cs:line 313

   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()

   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()

   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)

   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()

   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()

   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)

   at Tgstation.Server.Host.Core.ApplicationBuilderExtensions.<>c.<<UseCancelledRequestSuppression>b__2_0>d.MoveNext() in D:\tgstation-server\src\Tgstation.Server.Host\Core\ApplicationBuilderExtensions.cs:line 64

--- End of stack trace from previous location where exception was thrown ---

   at Tgstation.Server.Host.Core.ApplicationBuilderExtensions.<>c.<<UseDbConflictHandling>b__1_0>d.MoveNext() in D:\tgstation-server\src\Tgstation.Server.Host\Core\ApplicationBuilderExtensions.cs:line 38

--- End of stack trace from previous location where exception was thrown ---

   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)

   at Cyberboss.AspNetCore.AsyncInitializer.ApplicationBuilderExtensions.<>c__DisplayClass1_0.<<UseAsyncInitialization>b__2>d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by Cyberboss** [comment]
Fixed by #734
