### ISSUE TITLE
Issue with hard reset + test merge

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation-server#757]
```
System.InvalidOperationException: The instance of entity type 'User' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Nullable`1 forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode node, Boolean force)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode node, TState state, Func`3 handleNode)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
   at Tgstation.Server.Host.Controllers.RepositoryController.<>c__DisplayClass10_0.<<Update>b__13>d.MoveNext() in /src/src/Tgstation.Server.Host/Controllers/RepositoryController.cs:line 651
--- End of stack trace from previous location where exception was thrown ---
   at Tgstation.Server.Host.Controllers.RepositoryController.<>c__DisplayClass10_0.<<Update>b__13>d.MoveNext() in /src/src/Tgstation.Server.Host/Controllers/RepositoryController.cs:line 737
--- End of stack trace from previous location where exception was thrown ---
   at Tgstation.Server.Host.Core.JobManager.<>c__DisplayClass6_1.<<RunJob>g__RunJobInternal|2>d.MoveNext() in /src/src/Tgstation.Server.Host/Core/JobManager.cs:line 115
--- End of stack trace from previous location where exception was thrown ---
   at Tgstation.Server.Host.Core.JobManager.<>c__DisplayClass6_0.<<RunJob>g__HandleExceptions|1>d.MoveNext() in /src/src/Tgstation.Server.Host/Core/JobManager.cs:line 82
```

**Comment by Cyberboss** [comment]
Fixed by #759
