### ISSUE TITLE
Applying updates with the basic watchdog has to wait for the previous Compile Job to cleanup

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation-server#971]
```
[20:50:25] vrb: Tgstation.Server.Host.Controllers.BridgeController
    Bridge Request: {"commandType":3,"accessIdentifier":"uvAxalODjXNBrMpd4tZpjpgZfCOOUlPCBz8LFKgk"}
[20:50:25] vrb: Tgstation.Server.Host.Components.Watchdog.BasicWatchdog
    Monitor activation: ActiveServerRebooted
[20:50:25] dbg: Tgstation.Server.Host.Components.Watchdog.BasicWatchdog
    Next state action is to restart
[20:50:25] vrb: Tgstation.Server.Host.System.Process
    Terminating PID 14176...
[20:50:25] vrb: Tgstation.Server.Host.System.Process
    PID 14176 ended with code -1
[20:50:25] vrb: Tgstation.Server.Host.Components.InstanceManager
    Unregistered bridge handler: uvAxalODjXNBrMpd4tZpjpgZfCOOUlPCBz8LFKgk
[20:50:25] vrb: Tgstation.Server.Host.System.WindowsNetworkPromptReaper
    Unregistering process 14176...
[20:50:25] vrb: Tgstation.Server.Host.Components.Chat.ChatTrackingContext
    Deactivated
[20:50:25] dbg: Tgstation.Server.Host.Components.Deployment.DmbFactory
    Cleaning compile job 3 => 3efd7902-83c1-4859-972f-43eb1015ee44
[20:50:52] inf: Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider
    Attempting to reconnect provider...
[20:50:52] vrb: Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider
    Disconnecting...
[20:50:52] vrb: Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider
    Already disconnected not doing disconnection attempt!
[20:50:52] vrb: Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider
    Connecting...
[20:50:52] wrn: Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider
    Error connecting to Discord: Discord.Net.HttpException: The server responded with error 401: 401: Unauthorized
   at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
   at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
   at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
   at Discord.API.DiscordRestApiClient.SendAsync[TResponse](String method, String endpoint, String bucketId, ClientBucketType clientBucket, RequestOptions options)
   at Discord.API.DiscordRestApiClient.GetVoiceRegionsAsync(RequestOptions options)
   at Discord.WebSocket.DiscordSocketClient.OnLoginAsync(TokenType tokenType, String token)
   at Discord.Rest.BaseDiscordClient.LoginInternalAsync(TokenType tokenType, String token, Boolean validateToken)
   at Discord.Rest.BaseDiscordClient.LoginInternalAsync(TokenType tokenType, String token, Boolean validateToken)
   at Discord.Rest.BaseDiscordClient.LoginAsync(TokenType tokenType, String token, Boolean validateToken)
   at Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider.Connect(CancellationToken cancellationToken) in S:\Documents\Actual Documents\DA Git\tgstation-server\src\Tgstation.Server.Host\Components\Chat\Providers\DiscordProvider.cs:line 134
[20:51:08] vrb: Tgstation.Server.Host.Components.Watchdog.BasicWatchdog
    Begin LaunchImplNoLock
[20:51:08] vrb: Tgstation.Server.Host.Components.Deployment.DmbFactory
    Compile job 4 lock count now: 2
[20:51:08] vrb: Tgstation.Server.Host.Components.Chat.ChatTrackingContext
    Activated
[20:51:08] vrb: Tgstation.Server.Host.Components.Byond.ByondManager
    Creating ByondExecutableLock lock for version 513.1514.0
[20:51:08] vrb: Tgstation.Server.Host.Controllers.BridgeController
    Bridge Response: {}
[20:51:08] dbg: Tgstation.Server.Host.System.ProcessExecutor
    Launching process in S:\TGS4_INSTANCES\TGSTATION\Game\651a8bf1-6727-404e-8474-98589ee79b75\A: S:\TGS4_INSTANCES\TGSTATION\Byond\513.1514\byond\bin\dreamdaemon.exe tgstation.dmb -port 1337 -ports 1-65535 -close -trusted -public -public -params "server_service_version=5.0.0&tgs_port=5000&tgs_key=uuyypwo4E%2f9j%2fcSu64684bMia4E%2breIjk9qrBpKa"
[20:51:08] vrb: Tgstation.Server.Host.System.Process
    Created process ID: 11472
[20:51:08] vrb: Tgstation.Server.Host.System.WindowsNetworkPromptReaper
    Registering process 11472...
[20:51:08] vrb: Tgstation.Server.Host.Components.InstanceManager
    Registered bridge handler: uuyypwo4E/9j/cSu64684bMia4E+reIjk9qrBpKa
[20:51:08] dbg: Tgstation.Server.Host.Components.Watchdog.SessionController
    Created session controller. Primary: True, CommsKey: uuyypwo4E/9j/cSu64684bMia4E+reIjk9qrBpKa, Port: 1337
[20:51:08] vrb: Tgstation.Server.Host.System.Process
    Set PID 11472 to above normal priority
[20:51:23] vrb: Tgstation.Server.Host.Components.Chat.ChatTrackingContext
    Activated
[20:51:23] inf: Tgstation.Server.Host.Components.Watchdog.BasicWatchdog
    Launched servers successfully
[20:51:23] dbg: Tgstation.Server.Host.Components.Watchdog.BasicWatchdog
    Relaunch successful, resetting monitor state...
```

That's a whole minute before the new server is ready, not really acceptable

**Comment by Cyberboss** [comment]
Fixed in https://github.com/tgstation/tgstation-server/commit/af9ead2787cca24dc0383860f184776efc72596f
