### ISSUE TITLE
Instance onlining watchdog launching has the potential to delete the active compile job

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation-server#986]
```
[00:08:27]  [21:34:24] inf: Tgstation.Server.Host.Components.InstanceManager
[00:08:27]      tgstation-server-4.2.0
[00:08:27]  [21:34:24] vrb: Tgstation.Server.Host.Components.Repository.LibGit2RepositoryFactory
[00:08:27]      Creating in-memory libgit2 repository...
[00:08:27]  [21:34:24] vrb: Tgstation.Server.Host.Components.Repository.LibGit2RepositoryFactory
[00:08:27]      Successfully created in-memory libgit2 repository.
[00:08:27]  [21:34:24] dbg: Tgstation.Server.Host.Components.Byond.WindowsByondInstaller
[00:08:27]      Cleaning BYOND cache...
[00:08:27]  [21:34:24] dbg: Tgstation.Server.Host.Database.SqlServerDatabaseContext
[00:08:27]      No migrations to apply.
[00:08:27]  [21:34:24] vrb: Tgstation.Server.Host.Jobs.JobManager
[00:08:27]      Starting job manager...
[00:08:27]  [21:34:24] dbg: Tgstation.Server.Host.Jobs.JobManager
[00:08:27]      Job manager started!
[00:08:27]  [21:34:24] inf: Tgstation.Server.Host.Components.InstanceManager
[00:08:27]      Onlining instance ID 1 (IntegrationTestInstance) at C:/tgs4_test/401eb884-4d8f-4c4b-8738-17d64c57c073
[00:08:27]  [21:34:24] vrb: Tgstation.Server.Host.Server
[00:08:27]      Registering restart handler Tgstation.Server.Host.Components.Chat.ChatManager...
[00:08:27]  [21:34:24] vrb: Tgstation.Server.Host.Server
[00:08:27]      Registering restart handler Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog...
[00:08:27]  [21:34:24] vrb: Tgstation.Server.Host.Components.Byond.ByondManager
[00:08:27]      Deleting trusted .dmbs file C:\Users\appveyor\Documents\BYOND\cfg\trusted.txt
[00:08:27]  [21:34:24] vrb: Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider
[00:08:27]      Created.
[00:08:27]  [21:34:24] vrb: Tgstation.Server.Host.Components.Chat.Providers.IrcProvider
[00:08:27]      Created.
[00:08:27]  [21:34:24] vrb: Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider
[00:08:27]      Connecting...
[00:08:27]  [21:34:24] dbg: Tgstation.Server.Host.Components.Byond.ByondManager
[00:08:27]      Adding detected BYOND version 511.1385...
[00:08:27]  [21:34:24] vrb: Tgstation.Server.Host.Components.Deployment.DmbFactory
[00:08:27]      Loading compile job 1...
[00:08:27]  [21:34:24] vrb: Tgstation.Server.Host.Components.Deployment.DmbFactory
[00:08:27]      Compile job 1 lock count now: 1
[00:08:27]  [21:34:24] vrb: Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider
[00:08:27]      Logged in.
[00:08:27]  [21:34:24] vrb: Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider
[00:08:27]      Started.
[00:08:27]  [21:34:25] dbg: Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider
[00:08:27]      Connection established!
[00:08:27]  [21:34:45] wrn: Tgstation.Server.Host.Components.Chat.Providers.IrcProvider
[00:08:27]      Unable to connect to IRC: Meebey.SmartIrc4net.CouldNotConnectException: Could not connect to: irc.entropynet.net:6667 One or more errors occurred. (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. [::ffff:168.235.70.232]:6667)
[00:08:27]   ---> System.AggregateException: One or more errors occurred. (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. [::ffff:168.235.70.232]:6667)
[00:08:27]   ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. [::ffff:168.235.70.232]:6667
[00:08:27]     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
[00:08:27]     at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
[00:08:27]     at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
[00:08:27]     at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__27_1(IAsyncResult asyncResult)
[00:08:27]     at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
[00:08:27]     --- End of inner exception stack trace ---
[00:08:27]     at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
[00:08:27]     at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
[00:08:27]     at System.Threading.Tasks.Task.Wait()
[00:08:27]     at Meebey.SmartIrc4net.IrcConnection.Connect(String[] addresslist, Int32 port)
[00:08:27]     --- End of inner exception stack trace ---
[00:08:27]     at Meebey.SmartIrc4net.IrcConnection.Connect(String[] addresslist, Int32 port)
[00:08:27]     at Meebey.SmartIrc4net.IrcConnection.Connect(String address, Int32 port)
[00:08:27]     at Tgstation.Server.Host.Components.Chat.Providers.IrcProvider.<>c__DisplayClass22_0.<Connect>b__0() in C:\projects\tgstation-server-tools\src\Tgstation.Server.Host\Components\Chat\Providers\IrcProvider.cs:line 258
[00:08:27]  [21:34:45] vrb: Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider
[00:08:27]      Mapped channel 493119635319947269: asdf
[00:08:27]  [21:34:45] vrb: Tgstation.Server.Host.Components.Chat.ChatManager
[00:08:27]      Mapping channel Dextraspace:asdf as 1
[00:08:27]  [21:34:45] vrb: Tgstation.Server.Host.Components.Chat.ChatManager
[00:08:27]      Mapping channel irc.entropynet.net:\#botbus as 2
[00:08:27]  [21:34:45] dbg: Tgstation.Server.Host.Components.Session.ReattachInfoHandler
[00:08:27]      Reattach information not found!
[00:08:27]  [21:34:45] dbg: Tgstation.Server.Host.Jobs.JobManager
[00:08:27]      Starting job 18: Instance startup watchdog launch...
[00:08:27]  [21:34:45] vrb: Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog
[00:08:27]      Begin LaunchImplNoLock
[00:08:27]  [21:34:45] vrb: Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog
[00:08:27]      StopMonitor
[00:08:27]  [21:34:45] vrb: Tgstation.Server.Host.Components.Chat.ChatManager
[00:08:27]      Chat send "WD: Launching..." to channels: 1, 2
[00:08:27]  [21:34:45] vrb: Tgstation.Server.Host.Components.Deployment.DmbFactory
[00:08:27]      Compile job 1 lock count now: 2
[00:08:27]  [21:34:45] vrb: Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog
[00:08:27]      Prep for server launch. pendingSwappable is not available
[00:08:27]  [21:34:45] vrb: Tgstation.Server.Host.Components.Deployment.DmbFactory
[00:08:27]      Loading compile job 1...
[00:08:27]  [21:34:45] vrb: Tgstation.Server.Host.Components.Deployment.DmbFactory
[00:08:27]      Compile job 1 lock count now: 3
[00:08:27]  [21:34:45] vrb: Tgstation.Server.Host.Components.Chat.ChatTrackingContext
[00:08:27]      Activated
[00:08:27]  [21:34:45] vrb: Tgstation.Server.Host.Components.Byond.ByondManager
[00:08:27]      Creating ByondExecutableLock lock for version 511.1385
[00:08:27]  [21:34:45] dbg: Tgstation.Server.Host.System.ProcessExecutor
[00:08:27]      Launching process in C:\tgs4_test\401eb884-4d8f-4c4b-8738-17d64c57c073\Game\Live: C:\tgs4_test\401eb884-4d8f-4c4b-8738-17d64c57c073\Byond\511.1385\byond\bin\dreamdaemon.exe tests/DMAPI/BasicOperation/basic_operation_test.dmb -port 1337 -ports 1-65535 -close -safe -public -public -params "server_service_version=5.1.0&tgs_port=5001&tgs_key=UCyrl78tTXjjc43c1pZAhN05aRgqsElVUUcM%2fbOs"
[00:08:27]  [21:34:45] dbg: Tgstation.Server.Host.Components.Deployment.DmbFactory
[00:08:27]      Cleaning unused game folders: C:\tgs4_test\401eb884-4d8f-4c4b-8738-17d64c57c073\Game\09de636f-2233-486d-b490-b691cde27d45, C:\tgs4_test\401eb884-4d8f-4c4b-8738-17d64c57c073\Game\Live...
[00:08:27]  [21:34:45] inf: Tgstation.Server.Host.Components.InstanceManager
[00:08:27]      Server ready!
[00:08:27]  [21:34:45] dbg: Tgstation.Server.Host.System.WindowsNetworkPromptReaper
[00:08:27]      Starting network prompt reaper...
[00:08:27]  [21:34:45] dbg: Tgstation.Server.Host.Core.Application
[00:08:27]      Content Root: C:\projects\tgstation-server-tools\tests\Tgstation.Server.Tests\bin\Release\netcoreapp3.1
[00:08:27]  [21:34:45] vrb: Tgstation.Server.Host.Core.Application
[00:08:27]      Web Root: null
[00:08:27]  [21:34:45] dbg: Tgstation.Server.Host.Core.Application
[00:08:27]      Web control panel disabled!
[00:08:27]  [21:34:45] vrb: Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog
[00:08:27]      Running set to False
[00:08:27]  [21:34:45] vrb: Tgstation.Server.Host.Components.Deployment.DmbFactory
[00:08:27]      Compile job 1 lock count now: 2
[00:08:27]  [21:34:45] vrb: Tgstation.Server.Host.Components.Deployment.DmbFactory
[00:08:27]      Compile job 1 lock count now: 1
[00:08:27]  [21:34:45] wrn: Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog
[00:08:27]      Failed to start watchdog: System.ComponentModel.Win32Exception (267): The directory name is invalid.
[00:08:27]     at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
[00:08:27]     at System.Diagnostics.Process.Start()
[00:08:27]     at Tgstation.Server.Host.System.ProcessExecutor.LaunchProcess(String fileName, String workingDirectory, String arguments, Boolean readOutput, Boolean readError, Boolean noShellExecute) in C:\projects\tgstation-server-tools\src\Tgstation.Server.Host\System\ProcessExecutor.cs:line 150
[00:08:27]     at Tgstation.Server.Host.Components.Session.SessionControllerFactory.LaunchNew(IDmbProvider dmbProvider, IByondExecutableLock currentByondLock, DreamDaemonLaunchParameters launchParameters, Boolean primaryPort, Boolean primaryDirectory, Boolean apiValidate, CancellationToken cancellationToken) in C:\projects\tgstation-server-tools\src\Tgstation.Server.Host\Components\Session\SessionControllerFactory.cs:line 216
[00:08:27]     at Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.InitControllers(Action callBeforeRecurse, Task chatTask, DualReattachInformation reattachInfo, CancellationToken cancellationToken) in C:\projects\tgstation-server-tools\src\Tgstation.Server.Host\Components\Watchdog\BasicWatchdog.cs:line 263
[00:08:27]     at Tgstation.Server.Host.Components.Watchdog.WatchdogBase.LaunchImplNoLock(Boolean startMonitor, Boolean announce, DualReattachInformation reattachInfo, CancellationToken cancellationToken) in C:\projects\tgstation-server-tools\src\Tgstation.Server.Host\Components\Watchdog\WatchdogBase.cs:line 358
[00:08:27]  [21:34:45] vrb: Tgstation.Server.Host.Components.Chat.ChatManager
[00:08:27]      Chat send "WD: Startup failed!" to channels: 1, 2
[00:08:27]  [21:34:45] dbg: Tgstation.Server.Host.Jobs.JobManager
[00:08:27]      Job 18 exited with error! Exception: System.ComponentModel.Win32Exception (267): The directory name is invalid.
[00:08:27]     at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
[00:08:27]     at System.Diagnostics.Process.Start()
[00:08:27]     at Tgstation.Server.Host.System.ProcessExecutor.LaunchProcess(String fileName, String workingDirectory, String arguments, Boolean readOutput, Boolean readError, Boolean noShellExecute) in C:\projects\tgstation-server-tools\src\Tgstation.Server.Host\System\ProcessExecutor.cs:line 150
[00:08:27]     at Tgstation.Server.Host.Components.Session.SessionControllerFactory.LaunchNew(IDmbProvider dmbProvider, IByondExecutableLock currentByondLock, DreamDaemonLaunchParameters launchParameters, Boolean primaryPort, Boolean primaryDirectory, Boolean apiValidate, CancellationToken cancellationToken) in C:\projects\tgstation-server-tools\src\Tgstation.Server.Host\Components\Session\SessionControllerFactory.cs:line 216
[00:08:27]     at Tgstation.Server.Host.Components.Watchdog.BasicWatchdog.InitControllers(Action callBeforeRecurse, Task chatTask, DualReattachInformation reattachInfo, CancellationToken cancellationToken) in C:\projects\tgstation-server-tools\src\Tgstation.Server.Host\Components\Watchdog\BasicWatchdog.cs:line 263
[00:08:27]     at Tgstation.Server.Host.Components.Watchdog.WatchdogBase.LaunchImplNoLock(Boolean startMonitor, Boolean announce, DualReattachInformation reattachInfo, CancellationToken cancellationToken) in C:\projects\tgstation-server-tools\src\Tgstation.Server.Host\Components\Watchdog\WatchdogBase.cs:line 358
[00:08:27]     at Tgstation.Server.Host.Components.Watchdog.WatchdogBase.LaunchImplNoLock(Boolean startMonitor, Boolean announce, DualReattachInformation reattachInfo, CancellationToken cancellationToken) in C:\projects\tgstation-server-tools\src\Tgstation.Server.Host\Components\Watchdog\WatchdogBase.cs:line 393
[00:08:27]     at Tgstation.Server.Host.Components.Watchdog.WatchdogBase.<>c__DisplayClass75_0.<<StartAsync>b__1>d.MoveNext() in C:\projects\tgstation-server-tools\src\Tgstation.Server.Host\Components\Watchdog\WatchdogBase.cs:line 878
[00:08:27]  --- End of stack trace from previous location where exception was thrown ---
[00:08:27]     at Tgstation.Server.Host.Jobs.JobManager.<>c__DisplayClass7_0.<<RunJob>b__0>d.MoveNext() in C:\projects\tgstation-server-tools\src\Tgstation.Server.Host\Jobs\JobManager.cs:line 93
[00:08:27]  [21:34:45] dbg: Tgstation.Server.Host.Controllers.HomeController
[00:08:27]      Request made by User ID null. Api version: 6.2.0. User-Agent: Tgstation.Server.Tests/1.0.0.0. Type: POST. Route / to Instance null
[00:08:27]  [21:34:45] vrb: Tgstation.Server.Host.Security.WindowsSystemIdentityFactory
[00:08:27]      Invalid system identity/password combo for username Admin!
[00:08:27]  [21:34:46] dbg: Tgstation.Server.Host.Controllers.HomeController
[00:08:27]      Successfully logged in user 1!
[00:08:27]  [21:34:46] dbg: Tgstation.Server.Host.Controllers.JobController
[00:08:27]      Request made by User ID 1. Api version: 6.2.0. User-Agent: Tgstation.Server.Tests/1.0.0.0. Type: GET. Route /Job to Instance 1
[00:08:27]  [21:34:46] dbg: Tgstation.Server.Host.Controllers.DreamDaemonController
[00:08:27]      Request made by User ID 1. Api version: 6.2.0. User-Agent: Tgstation.Server.Tests/1.0.0.0. Type: GET. Route /DreamDaemon to Instance 1
[00:08:27]  [21:34:46] vrb: Tgstation.Server.Host.Components.Deployment.DmbFactory
[00:08:27]      Compile job 1 lock count now: 1
[00:08:27]  TEST ERROR: Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException in flight!
[00:08:27]  [21:34:46] inf: Tgstation.Server.Host.Server
[00:08:27]      Server termination requested!
[00:08:27]  [21:34:46] vrb: Tgstation.Server.Host.System.WindowsNetworkPromptReaper
[00:08:27]      Stopping network prompt reaper...
[00:08:27]  [21:34:46] vrb: Tgstation.Server.Host.System.WindowsNetworkPromptReaper
[00:08:27]      Cancelled!
[00:08:27]  [21:34:46] dbg: Tgstation.Server.Host.System.WindowsNetworkPromptReaper
[00:08:27]      Exiting network prompt reaper...
[00:08:27]  [21:34:46] vrb: Tgstation.Server.Host.Components.Chat.ChatManager
[00:08:27]      Message processing loop cancelled!
[00:08:27]  [21:34:46] vrb: Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider
[00:08:27]      Disconnecting...
[00:08:27]  [21:34:46] vrb: Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider
[00:08:27]      Stopped.
[00:08:27]  [21:34:46] dbg: Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider
[00:08:27]      Disconnected!
[00:08:27]  [21:34:46] vrb: Tgstation.Server.Host.Security.IdentityCache
[00:08:27]      Disposing...
[00:08:27]  [21:34:46] vrb: Tgstation.Server.Host.Components.Chat.Providers.DiscordProvider
[00:08:27]      Disposed
[00:08:27]  [21:34:46] vrb: Tgstation.Server.Host.Components.Chat.Providers.IrcProvider
[00:08:27]      Disposed
[00:08:27]  [21:34:46] vrb: Tgstation.Server.Host.Components.Watchdog.WindowsWatchdog
[00:08:27]      Running set to False
[00:08:27]  [21:34:46] vrb: Tgstation.Server.Host.Components.Repository.RepositoryManager
[00:08:27]      Disposing...
```

**Comment by Cyberboss** [comment]
Fixed in above PR
