### ISSUE TITLE
Cannot drop instance because of database constraints

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation-server#995]
```
Jay ͔Today at 7:04 PM
Oh right. There's a server instance I can't remove
 [23:04:30]: DELETE http://localhost:38603/Instance/2
 [23:04:31]: HTTP Conflict: DELETE http://localhost:38603/Instance/2 => {"serverApiVersion":"6.3.0","message":"The operation could not be performed as it would violate database integrity. Please retry the request, making sure to not duplicate field names with existing entities.","additionalData":"Cannot delete or update a parent row: a foreign key constraint fails (`feedback`.`compilejobs`, CONSTRAINT `FK_CompileJobs_RevisionInformations_RevisionInformationId` FOREIGN KEY (`RevisionInformationId`) REFERENCES `revisioninformations` (`Id`))","errorCode":6}
 [23:04:31]: UNCAUGHT COMMAND EXCEPTION! Type: InstanceCommand Action: Delete Exception: Tgstation.Server.Client.ConflictException: The operation could not be performed as it would violate database integrity. Please retry the request, making sure to not duplicate field names with existing entities.
    at Tgstation.Server.Client.ApiClient.HandleBadResponse(HttpResponseMessage response, String json)
    at Tgstation.Server.Client.ApiClient.<RunRequest>d__16`1.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at Tgstation.Server.ControlPanel.ViewModels.InstanceViewModel.<RunCommand>d__92.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at Tgstation.Server.ControlPanel.ViewModels.EnumCommand`1.<Execute>d__8.MoveNext()
```

Ugh

**Comment by Cyberboss** [comment]
Requesting a database dump from Cit host to debug

**Comment by Cyberboss** [comment]
Dump attached 
[server.zip](https://github.com/tgstation/tgstation-server/files/4646096/server.zip)

**Comment by Cyberboss** [comment]
Attempting to delete that with latest code succeeds successfully

**Comment by Cyberboss** [comment]
This has been repro'd with Postgres
